# Generated by Django 6.0.1 on 2026-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='meals',
            field=models.JSONField(default=list),
        ),
    ]
