# Generated by Django 6.0.1 on 2026-03-06 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_dietplan'),
        ('diets', '0002_dietplan_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('water_consumed', models.FloatField(default=0.0)),
                ('completed_meals', models.JSONField(default=list)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='accounts.member')),
            ],
            options={
                'db_table': 'GymMate_daily_progress',
                'unique_together': {('member', 'date')},
            },
        ),
    ]
