# Generated by Django 6.0 on 2026-01-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='GymMate_Users',
        ),
    ]
