# Generated by Django 6.0.1 on 2026-03-05 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workoutplan_day_workoutplan_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembersAttendance',
            new_name='MemberAttendance',
        ),
        migrations.AlterModelTable(
            name='memberattendance',
            table='GymMate_member_attendance',
        ),
        migrations.CreateModel(
            name='TrainerAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.trainer')),
            ],
            options={
                'db_table': 'GymMate_trainer_attendance',
                'unique_together': {('trainer', 'date')},
            },
        ),
    ]
