# Generated by Django 6.0.1 on 2026-03-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_membersattendance_memberattendance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
    ]
