# Generated by Django 6.0.1 on 2026-03-06 06:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField(blank=True, null=True)),
                ('muscle_mass', models.FloatField(blank=True, null=True)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='accounts.member')),
            ],
            options={
                'db_table': 'GymMate_member_progress',
                'ordering': ['-date'],
            },
        ),
    ]
