# Generated by Django 6.0.1 on 2026-03-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_memberprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprogress',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
