# Generated by Django 6.0.1 on 2026-03-06 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_memberprogress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprogress',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
