# Generated by Django 6.0.1 on 2026-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_memberprogress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
