# Generated by Django 5.2.9 on 2026-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermembership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
