# Generated by Django 6.0.1 on 2026-03-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_membermembership_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='accounts.trainerattendance')),
            ],
            options={
                'db_table': 'GymMate_trainer_breaks',
            },
        ),
    ]
